from pathlib import Path
import os


def env_bool(name: str, default: str = "0") -> bool:
    return str(os.getenv(name, default)).strip().lower() in {"1", "true", "yes", "on"}

APP_NAME = "Koju Dhan Algo"
DATA_DIR = Path("data")
STATE_FILE = DATA_DIR / "state.json"
PREMARKET_FILE = DATA_DIR / "premarket_cache.json"
PREMARKET_REPORT_FILE = DATA_DIR / "premarket_cache_report.json"
TRADE_LEDGER_FILE = DATA_DIR / "trade_ledger.json"
SCRIP_MASTER_FILE = DATA_DIR / "dhan_scrip_master.csv"
RUNTIME_SNAPSHOT_FILE = DATA_DIR / "runtime_snapshot.json"
RECONCILE_SNAPSHOT_FILE = DATA_DIR / "reconcile_snapshot.json"
ENGINE_COMMANDS_FILE = DATA_DIR / "engine_commands.jsonl"
RECONCILE_COMMANDS_FILE = DATA_DIR / "reconcile_commands.jsonl"
ENGINE_COMMAND_STATE_FILE = DATA_DIR / "engine_command_state.json"
RECONCILE_COMMAND_STATE_FILE = DATA_DIR / "reconcile_command_state.json"
RECONCILED_CANDLES_FILE = DATA_DIR / "reconciled_candles.json"

DHAN_API_BASE_URL = "https://api.dhan.co/v2"
DHAN_SCRIP_MASTER_URL = "https://images.dhan.co/api-data/api-scrip-master.csv"
DHAN_FEED_URL = "wss://api-feed.dhan.co?version=2&token={token}&clientId={client_id}&authType=2"
DHAN_ORDER_UPDATE_URL = "wss://api-order-update.dhan.co"

IST_TIMEZONE = "Asia/Kolkata"
MARKET_OPEN = "09:15"
MARKET_CLOSE = "15:30"

FETCH_REQUESTS_PER_SECOND = int(os.getenv("DHAN_FETCH_RPS", "1"))
ORDER_REQUESTS_PER_SECOND = 8
BROKER_REQUESTS_PER_SECOND = int(os.getenv("DHAN_BROKER_RPS", "2"))
FETCH_RETRY_ATTEMPTS = int(os.getenv("DHAN_FETCH_RETRY_ATTEMPTS", "6"))
FETCH_RETRY_BASE_SECONDS = float(os.getenv("DHAN_FETCH_RETRY_BASE_SECONDS", "5"))
FETCH_RETRY_MAX_SECONDS = float(os.getenv("DHAN_FETCH_RETRY_MAX_SECONDS", "60"))
TICK_QUEUE_MAXSIZE = int(os.getenv("TICK_QUEUE_MAXSIZE", "300000"))
TICK_QUEUE_WARN_INTERVAL_SECONDS = float(os.getenv("TICK_QUEUE_WARN_INTERVAL_SECONDS", "5"))
EXECUTION_WORKER_COUNT = int(os.getenv("EXECUTION_WORKER_COUNT", "4"))
DHAN_CONNECT_TIMEOUT_SECONDS = float(os.getenv("DHAN_CONNECT_TIMEOUT_SECONDS", "5"))
DHAN_READ_TIMEOUT_SECONDS = float(os.getenv("DHAN_READ_TIMEOUT_SECONDS", "12"))
ORDER_SOCKET_OPEN_TIMEOUT_SECONDS = float(os.getenv("ORDER_SOCKET_OPEN_TIMEOUT_SECONDS", "30"))
ORDER_SOCKET_PING_INTERVAL_SECONDS = float(os.getenv("ORDER_SOCKET_PING_INTERVAL_SECONDS", "20"))
ORDER_SOCKET_PING_TIMEOUT_SECONDS = float(os.getenv("ORDER_SOCKET_PING_TIMEOUT_SECONDS", "20"))
ORDER_SOCKET_RECONNECT_BASE_SECONDS = float(os.getenv("ORDER_SOCKET_RECONNECT_BASE_SECONDS", "5"))
ORDER_SOCKET_RECONNECT_MAX_SECONDS = float(os.getenv("ORDER_SOCKET_RECONNECT_MAX_SECONDS", "45"))
STARTUP_BROKER_RECONCILE_TIMEOUT_SECONDS = float(os.getenv("STARTUP_BROKER_RECONCILE_TIMEOUT_SECONDS", "8"))
BROKER_RECONCILE_TIMEOUT_SECONDS = float(os.getenv("BROKER_RECONCILE_TIMEOUT_SECONDS", "75"))
BROKER_POSITIONS_TIMEOUT_SECONDS = float(os.getenv("BROKER_POSITIONS_TIMEOUT_SECONDS", "35"))
BROKER_TRADE_BOOK_TIMEOUT_SECONDS = float(os.getenv("BROKER_TRADE_BOOK_TIMEOUT_SECONDS", "20"))
BROKER_ORDER_BOOK_TIMEOUT_SECONDS = float(os.getenv("BROKER_ORDER_BOOK_TIMEOUT_SECONDS", "20"))
BROKER_PENDING_RECOVERY_TIMEOUT_SECONDS = float(os.getenv("BROKER_PENDING_RECOVERY_TIMEOUT_SECONDS", "10"))
BROKER_PENDING_LOOKUP_LIMIT = int(os.getenv("BROKER_PENDING_LOOKUP_LIMIT", "3"))
ALLOW_POSITIONS_ONLY_RECONCILE = env_bool("ALLOW_POSITIONS_ONLY_RECONCILE", "1")
START_API_TIMEOUT_SECONDS = float(os.getenv("START_API_TIMEOUT_SECONDS", "20"))
MAX_MARKET_FEED_CONNECTIONS = 5
MAX_INSTRUMENTS_PER_CONNECTION = 5000
MAX_SUBSCRIBE_BATCH = 100
ENGINE_SNAPSHOT_INTERVAL_SECONDS = float(os.getenv("ENGINE_SNAPSHOT_INTERVAL_SECONDS", "0.5"))
ENGINE_COMMAND_POLL_SECONDS = float(os.getenv("ENGINE_COMMAND_POLL_SECONDS", "0.25"))
RECONCILE_COMMAND_POLL_SECONDS = float(os.getenv("RECONCILE_COMMAND_POLL_SECONDS", "1"))
RECONCILE_CANDLE_INTERVAL_SECONDS = float(os.getenv("RECONCILE_CANDLE_INTERVAL_SECONDS", "60"))
RECONCILE_BROKER_INTERVAL_SECONDS = float(os.getenv("RECONCILE_BROKER_INTERVAL_SECONDS", "180"))
RUNTIME_SNAPSHOT_STALE_SECONDS = float(os.getenv("RUNTIME_SNAPSHOT_STALE_SECONDS", "10"))
